services: 
  mongo:
    image: mongo:latest
    container_name: mongoDb
    volumes:
      - mongo_data:/data/db
  
  backend: 
    image: dhanraj11/simple-testing-backend:latest
    container_name: backend_container
    ports:
      - " 3000:3000"
    depends_on:
      - mongo
  
  frontend: 
    image: dhanraj11/simple-testing-frontend:latest
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: